### ISSUE TITLE
Member missing in LinearRegression

### ISSUE THREAD

**Issue by gocamiot** [chrisbartley/aq-buzz#1]
Hey. I came across this code to get some temp readings from feather. It looks very neat well done.
I copied paste and getting compile error:
07:33: error: 'class LinearRegression' has no member named 'parameters'
  207 |                linearRegression.parameters(slopeAndIntercept);
      |                                 ^~~~~~~~~~
exit status 1
'class LinearRegression' has no member named 'parameters'

I have added this to libraries and not getting a library not found error: https://github.com/cubiwan/Regressino

Please help.

regards
Jakes

**Comment by chrisbartley** [comment]
Have you tried Regressino's examples?  This one in particular which uses the `parameters` function:

https://github.com/cubiwan/Regressino/blob/master/examples/linear/linear.ino

If you still can't get it working, maybe try asking over there.  I don't really know anything about the Regressino library other than it worked for me at the time 🤷‍♂️
